name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./second
          push: true
          tags: andrewfreak/my_app:latest

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          status: ${{ job.status }}
          channel-id: C088BKGQ92T
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
