name: Kubernetes Cluster Monitoring

# Триггеры событий
on:
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub Actions
  push:
    branches:
      - main  # Запуск при пуше в ветку main
  pull_request:
    branches:
      - main  # Запуск при создании пул-реквеста в ветку main

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Check pod status
        id: pod-status
        run: |
          # Получаем список всех подов и фильтруем те, которые не в состоянии "Running"
          FAILED_PODS=$(kubectl get pods --all-namespaces --field-selector=status.phase!=Running -o json)
          echo "Failed pods:"
          echo "$FAILED_PODS"

          # Если есть неработающие поды, завершаем шаг с ошибкой
          if [ -n "$FAILED_PODS" ]; then
            echo "::set-output name=has_failed_pods::true"
            echo "Обнаружены неработающие модули!"
            exit 1
          else
            echo "::set-output name=has_failed_pods::false"
            echo "Все модули работают нормально."
          fi

      - name: Notify Slack on failure
        if: steps.pod-status.outputs.has_failed_pods == 'true'
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: "Ошибка в кластере Kubernetes: обнаружены неработающие модули."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
