name: Kubernetes Status Check

on:
  push:
    branches:
      - main  

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_K8S }}" > ~/.kube/config

      - name: Check Kubernetes status
        run: |
          kubectl get pods --all-namespaces --field-selector=status.phase!=Running > status.txt || true
          if [ -s status.txt ]; then
            echo "Pods not running. Sending notification to Slack."
            message=$(cat status.txt | awk '{print $0}' | jq -R . | jq -s .)  # Преобразуем вывод в JSON
            payload="{\"text\":\"Kubernetes issues detected:\n${message}\"}"  # Формируем payload
            echo "Payload to Slack: $payload"  # Логируем payload для отладки
            response=$(curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK_URL)
            echo "Slack response: $response"  # Логируем ответ от Slack
          else
            echo "All pods are running."
          fi
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
